"""updated student orm

Revision ID: d1abf1ddbc72
Revises: 
Create Date: 2025-01-06 13:34:10.324894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1abf1ddbc72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name='students_pkey')
    )
    # ### end Alembic commands ###
